name: 'Unity Cloud Build Action'
description: 'Allows to start a build on Unity Cloud Build, and await its result'
author: 'Elmar Jansen'
inputs:
  orgid: 
    required: true
    description: 'Organisation ID'
  projectid: # change this
    required: true
    description: 'Project ID'
  projectid: # change this
    required: true
    description: 'Build Target ID'
runs:
  using: 'node12'
  main: 'dist/index.js'
